### ISSUE TITLE
problems with --ignore

### ISSUE THREAD

**Issue by cvlmtg** [ggreer/the_silver_searcher#385]
what's the format of the --ignore pattern? If I do

```
ag --ignore '*.min.js' time website/public/vendor/ | less
```

ag still looks into _website/public/vendor/jquery-ui.min.js_

I've tried also '.*\.min\.js', '.min.js$' etc with no results.
I'm on OSX 10.9 with ag compiled through homebrew.

**Comment by eksperimental** [comment]
As of version 0.28.0
```sh
$ ag -l -U --ignore '/doc/' '~r/./' elixir/*
elixir/doc/elixir/Kernel.html
elixir/lib/elixir/lib/kernel.ex
elixir/lib/elixir/test/elixir/kernel_test.exs

$ ag -l -U --ignore '/doc/' '~r/./' elixir/
elixir/lib/elixir/lib/kernel.ex
elixir/lib/elixir/test/elixir/kernel_test.exs
```

the * at the end of the PATH breaks the `--ignore` argument.

**Comment by ggreer** [comment]
@eksperimental Two things:

1. You put a forward slash in your ignore pattern, which means, "Only ignore at the root level." This isn't causing a problem in your example, but it's worth noting.

2. Ag doesn't see the star in the first example. Bash or zsh expansion is passing `elixer/doc` (among other paths) to ag.

**Comment by eksperimental** [comment]
sorry greg, i didn't understand No. 2
thanks for answering,
but it is still no clear what should be the pattern to ignore any result that contains a folder named doc ?
--ignore '.*/doc/.*'

if so, it is not working:
```
$ ag -U -l --ignore '.*/doc/.*' '~r/./' elixir
elixir/lib/elixir/lib/kernel.ex
elixir/lib/elixir/lib/regex.ex
elixir/lib/elixir/test/elixir/kernel_test.exs
elixir/doc/elixir/+Kernel.html
elixir/doc/elixir/Regex.html
elixir/doc/elixir/Kernel.html
```

the only one that seems to work is:
```
$ ag -U -l --ignore 'doc/' '~r/./' elixir
elixir/lib/elixir/lib/kernel.ex
elixir/lib/elixir/lib/regex.ex
elixir/lib/elixir/test/elixir/kernel_test.exs
```
which is wrong according to your definition above, because the path of the ignored files does not start with "doc/"

thank!

**Comment by ggreer** [comment]
In the first example of your previous comment, you put a forward slash at the *start* of your ignore pattern. That is, the pattern started with `/`. If it starts with `/`, that means "ignore only in the current directory. If it *ends* in a `/`, that means "only match if it's a directory."

Examples:

* `doc` ignores any file or directory anywhere that is called "doc".

* `/doc` ignores any file or directory in the root dir called "doc".

* `doc/` ignores any directory any where that's called "doc".

* `/doc/` ignores any directory in the root called "doc".

These examples are typical behavior for .gitignore and .hgignore. Ag isn't doing anything strange here.

Second point: If you run `ag blah elxir`, that's the same as `cd elixer && ag blah`. That means "doc" is in the root. An ignore pattern like `.*/doc/.*` only match doc directories in a sub-directory.

**Comment by eksperimental** [comment]
thanks @ggreer it is a bit more clear now.
I think you should put in the documentation what kind of pattern it expects, 
seems you use the same word (PATTERN) do describe the search PATTERN (regex).
I searched the respository and there's not reference to fnmatch().

so answering myself.
`$ag -U -l --ignore 'doc/' '~r/./' elixir/`
is the right command.

thanks for creating `ag`, I use it every day I'm with the computer pretty much

**Comment by shreevatsar** [comment]
This still doesn't seem to be working, with `ag version 0.30.0` (the latest available on Homebrew).

This is my .agignore file:
```
min.js
*.min.js
*/*.min.js
*/*/*.min.js
*/*/*/*.min.js
*/*/*/*.min.js
```

and yet `ag -l` includes files like `client-app/bower_components/ember/ember.min.js`. What's going on?

I notice that putting `*.js` in my `.agignore` (even with nothing else) prevents `ag` from examining such a file.

**Comment by decaff** [comment]
FYI.  If an ignore pattern is set as '*.min.js' and the patch from #680 (by @epmatsw) is applied, the complaints about ag not ignoring .min.js files should be fixed.  Example:
````
$ ls
jj.js  jj.min.js
$ ../ag  --ignore '*.min.js' -g 'js' -l
jj.js
$
````

**Comment by shreevatsar** [comment]
@decaff What is preventing #680 from being merged and released as part of ag?

I see lots of bugs (#413, #678 and this one #385) referencing this issue.

**Comment by decaff** [comment]
@shreevatsar I think the author is [very busy](http://geoff.greer.fm/2014/10/13/help-me-get-to-ag-10/).  Just a guess.

**Comment by lencioni** [comment]
I seem to be having luck with `**.min.js` or `**.min.*`

**Comment by arichiardi** [comment]
I confirm that `**.js` works on `ag version 0.31.0` but `**/*.js` like `.gitignore` still does not.
